#---------------------------------------------------------------------
package Finance::QBXML;
#
# Copyright 2010 Christopher J. Madsen
#
# Author: Christopher J. Madsen <perl@cjmweb.net>
# Created: February 2, 2010
#
# This program is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See either the
# GNU General Public License or the Artistic License for more details.
#
# ABSTRACT: Read and write QuickBooks qbXML
#---------------------------------------------------------------------

use 5.008;
use Moose;
use MooseX::Types::Moose qw(Int Str);

use Carp 'croak';
use Scalar::Util 'reftype';

#=====================================================================
# Package Global Variables:

our $VERSION = '0.01';

# %childElements and %mayRepeat are generated by tools/parseSchema.pl:

# qbXML requires that elements be listed in a particular order:
our %childElements = (
  APAccountRef => [qw(
    ListID
    FullName
  )],
  ARAccountRef => [qw(
    ListID
    FullName
  )],
  ARRefundCreditCardAdd => [qw(
    CustomerRef
    RefundFromAccountRef
    ARAccountRef
    TxnDate
    RefNumber
    Address
    PaymentMethodRef
    Memo
    CreditCardTxnInfo
    RefundAppliedToTxnAdd
  )],
  ARRefundCreditCardAddRq => [qw(
    ARRefundCreditCardAdd
    IncludeRetElement
  )],
  ARRefundCreditCardQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  AccountAdd => [qw(
    Name
    IsActive
    ParentRef
    AccountType
    DetailAccountType
    AccountNumber
    BankNumber
    Desc
    OpenBalance
    OpenBalanceDate
    SalesTaxCodeRef
    TaxLineID
    CurrencyRef
  )],
  AccountAddRq => [qw(
    AccountAdd
    IncludeRetElement
  )],
  AccountFilter => [qw(
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  AccountMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    AccountType
    AccountNumber
    BankNumber
    Desc
    OpenBalance
    OpenBalanceDate
    SalesTaxCodeRef
    TaxLineID
    CurrencyRef
  )],
  AccountModRq => [qw(
    AccountMod
    IncludeRetElement
  )],
  AccountQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    AccountType
    CurrencyFilter
    IncludeRetElement
    OwnerID
  )],
  AccountRef => [qw(
    ListID
    FullName
  )],
  Address => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    Addr5
    City
    State
    PostalCode
    Country
    Note
  )],
  AgingReportQueryRq => [qw(
    AgingReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    IncludeColumn
    IncludeAccounts
    ReportAgingAsOf
  )],
  AppliedToTxnAdd => [qw(
    TxnID
    PaymentAmount
    TxnLineDetail
    SetCredit
    DiscountAmount
    DiscountAccountRef
  )],
  AppliedToTxnMod => [qw(
    TxnID
    PaymentAmount
    SetCredit
    DiscountAmount
    DiscountAccountRef
  )],
  ApplyCheckToTxnAdd => [qw(
    TxnID
    Amount
  )],
  ApplyCheckToTxnMod => [qw(
    TxnID
    Amount
  )],
  AssetAccountRef => [qw(
    ListID
    FullName
  )],
  BankAccountRef => [qw(
    ListID
    FullName
  )],
  BaseUnit => [qw(
    Name
    Abbreviation
  )],
  BillAdd => [qw(
    VendorRef
    APAccountRef
    TxnDate
    DueDate
    RefNumber
    TermsRef
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    LinkToTxnID
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  BillAddRq => [qw(
    BillAdd
    IncludeRetElement
  )],
  BillAddress => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    Addr5
    City
    State
    PostalCode
    Country
    Note
  )],
  BillMod => [qw(
    TxnID
    EditSequence
    VendorRef
    APAccountRef
    TxnDate
    DueDate
    RefNumber
    TermsRef
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  BillModRq => [qw(
    BillMod
    IncludeRetElement
  )],
  BillPaymentCheckAdd => [qw(
    PayeeEntityRef
    APAccountRef
    TxnDate
    BankAccountRef
    IsToBePrinted
    RefNumber
    Memo
    ExchangeRate
    AppliedToTxnAdd
  )],
  BillPaymentCheckAddRq => [qw(
    BillPaymentCheckAdd
    IncludeRetElement
  )],
  BillPaymentCheckMod => [qw(
    TxnID
    EditSequence
    TxnDate
    BankAccountRef
    Amount
    ExchangeRate
    IsToBePrinted
    RefNumber
    Memo
    AppliedToTxnMod
  )],
  BillPaymentCheckModRq => [qw(
    BillPaymentCheckMod
    IncludeRetElement
  )],
  BillPaymentCheckQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  BillPaymentCreditCardAdd => [qw(
    PayeeEntityRef
    APAccountRef
    TxnDate
    CreditCardAccountRef
    RefNumber
    Memo
    ExchangeRate
    AppliedToTxnAdd
  )],
  BillPaymentCreditCardAddRq => [qw(
    BillPaymentCreditCardAdd
    IncludeRetElement
  )],
  BillPaymentCreditCardQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  BillQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    PaidStatus
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  BillToPayQueryRq => [qw(
    PayeeEntityRef
    APAccountRef
    DueDate
    CurrencyFilter
    IncludeRetElement
  )],
  BillingRateAdd => [qw(
    Name
    FixedBillingRate
    BillingRatePerItem
  )],
  BillingRateAddRq => [qw(
    BillingRateAdd
    IncludeRetElement
  )],
  BillingRatePerItem => [qw(
    ItemRef
    CustomRate
    CustomRatePercent
    AdjustPercentage
    AdjustBillingRateRelativeTo
  )],
  BillingRateQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    ItemRef
    IncludeRetElement
  )],
  BillingRateRef => [qw(
    ListID
    FullName
  )],
  BudgetSummaryReportQueryRq => [qw(
    BudgetSummaryReportType
    DisplayReport
    FiscalYear
    BudgetCriterion
    SummarizeBudgetColumnsBy
    SummarizeBudgetRowsBy
  )],
  BuildAssemblyAdd => [qw(
    ItemInventoryAssemblyRef
    TxnDate
    RefNumber
    Memo
    QuantityToBuild
    MarkPendingIfRequired
  )],
  BuildAssemblyAddRq => [qw(
    BuildAssemblyAdd
    IncludeRetElement
  )],
  BuildAssemblyMod => [qw(
    TxnID
    EditSequence
    TxnDate
    RefNumber
    Memo
    QuantityToBuild
    MarkPendingIfRequired
    RemovePending
  )],
  BuildAssemblyModRq => [qw(
    BuildAssemblyMod
    IncludeRetElement
  )],
  BuildAssemblyQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    ItemFilter
    RefNumberFilter
    RefNumberRangeFilter
    PendingStatus
    IncludeComponentLineItems
    IncludeRetElement
    OwnerID
  )],
  COGSAccountRef => [qw(
    ListID
    FullName
  )],
  COMCallbackInfo => [qw(
    AppName
    ProgID
    CLSID
  )],
  CashBackInfoAdd => [qw(
    AccountRef
    Memo
    Amount
  )],
  CashBackInfoMod => [qw(
    AccountRef
    Memo
    Amount
  )],
  CategoryAccountMappingMod => [qw(
    MappingCategory
    MappingAccount
    Threshold
  )],
  ChargeAdd => [qw(
    CustomerRef
    TxnDate
    RefNumber
    ItemRef
    Quantity
    UnitOfMeasure
    Rate
    Amount
    Desc
    ARAccountRef
    ClassRef
    BilledDate
    DueDate
    OverrideItemAccountRef
  )],
  ChargeAddRq => [qw(
    ChargeAdd
    IncludeRetElement
  )],
  ChargeMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    TxnDate
    RefNumber
    ItemRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    Amount
    Desc
    ARAccountRef
    ClassRef
    BilledDate
    DueDate
    OverrideItemAccountRef
  )],
  ChargeModRq => [qw(
    ChargeMod
    IncludeRetElement
  )],
  ChargeQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    PaidStatus
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  CheckAdd => [qw(
    AccountRef
    PayeeEntityRef
    RefNumber
    TxnDate
    Memo
    Address
    IsToBePrinted
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ApplyCheckToTxnAdd
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  CheckAddRq => [qw(
    CheckAdd
    IncludeRetElement
  )],
  CheckMod => [qw(
    TxnID
    EditSequence
    AccountRef
    PayeeEntityRef
    RefNumber
    TxnDate
    Memo
    Address
    IsToBePrinted
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ApplyCheckToTxnMod
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  CheckModRq => [qw(
    CheckMod
    IncludeRetElement
  )],
  CheckQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  ClassAdd => [qw(
    Name
    IsActive
    ParentRef
  )],
  ClassAddRq => [qw(
    ClassAdd
    IncludeRetElement
  )],
  ClassMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
  )],
  ClassModRq => [qw(
    ClassMod
    IncludeRetElement
  )],
  ClassQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  ClassRef => [qw(
    ListID
    FullName
  )],
  ClearedStatusMod => [qw(
    TxnID
    TxnLineID
    ClearedStatus
  )],
  ClearedStatusModRq => [qw(
    ClearedStatusMod
  )],
  CompanyActivityQueryRq => [qw(
    IncludeRetElement
  )],
  CompanyFileEventSubscription => [qw(
    CompanyFileEventOperation
  )],
  CompanyQueryRq => [qw(
    IncludeRetElement
    OwnerID
  )],
  CreditCardAccountRef => [qw(
    ListID
    FullName
  )],
  CreditCardChargeAdd => [qw(
    AccountRef
    PayeeEntityRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  CreditCardChargeAddRq => [qw(
    CreditCardChargeAdd
    IncludeRetElement
  )],
  CreditCardChargeMod => [qw(
    TxnID
    EditSequence
    AccountRef
    PayeeEntityRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  CreditCardChargeModRq => [qw(
    CreditCardChargeMod
    IncludeRetElement
  )],
  CreditCardChargeQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  CreditCardCreditAdd => [qw(
    AccountRef
    PayeeEntityRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  CreditCardCreditAddRq => [qw(
    CreditCardCreditAdd
    IncludeRetElement
  )],
  CreditCardCreditMod => [qw(
    TxnID
    EditSequence
    AccountRef
    PayeeEntityRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  CreditCardCreditModRq => [qw(
    CreditCardCreditMod
    IncludeRetElement
  )],
  CreditCardCreditQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  CreditCardInfo => [qw(
    CreditCardNumber
    ExpirationMonth
    ExpirationYear
    NameOnCard
    CreditCardAddress
    CreditCardPostalCode
  )],
  CreditCardTxnInfo => [qw(
    CreditCardTxnInputInfo
    CreditCardTxnResultInfo
  )],
  CreditCardTxnInfoMod => [qw(
    CreditCardTxnInputInfoMod
    CreditCardTxnResultInfoMod
  )],
  CreditCardTxnInputInfo => [qw(
    CreditCardNumber
    ExpirationMonth
    ExpirationYear
    NameOnCard
    CreditCardAddress
    CreditCardPostalCode
    CommercialCardCode
    TransactionMode
    CreditCardTxnType
  )],
  CreditCardTxnInputInfoMod => [qw(
    CreditCardNumber
    ExpirationMonth
    ExpirationYear
    NameOnCard
    CreditCardAddress
    CreditCardPostalCode
    CommercialCardCode
    TransactionMode
    CreditCardTxnType
  )],
  CreditCardTxnResultInfo => [qw(
    ResultCode
    ResultMessage
    CreditCardTransID
    MerchantAccountNumber
    AuthorizationCode
    AVSStreet
    AVSZip
    CardSecurityCodeMatch
    ReconBatchID
    PaymentGroupingCode
    PaymentStatus
    TxnAuthorizationTime
    TxnAuthorizationStamp
    ClientTransID
  )],
  CreditCardTxnResultInfoMod => [qw(
    ResultCode
    ResultMessage
    CreditCardTransID
    MerchantAccountNumber
    AuthorizationCode
    AVSStreet
    AVSZip
    CardSecurityCodeMatch
    ReconBatchID
    PaymentGroupingCode
    PaymentStatus
    TxnAuthorizationTime
    TxnAuthorizationStamp
    ClientTransID
  )],
  CreditMemoAdd => [qw(
    CustomerRef
    ClassRef
    ARAccountRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    CreditMemoLineAdd
    CreditMemoLineGroupAdd
    DiscountLineAdd
    SalesTaxLineAdd
    ShippingLineAdd
  )],
  CreditMemoAddRq => [qw(
    CreditMemoAdd
    IncludeRetElement
  )],
  CreditMemoLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    IsTaxable
    OverrideItemAccountRef
    Other1
    Other2
    CreditCardTxnInfo
    DataExt
  )],
  CreditMemoLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    ServiceDate
    DataExt
  )],
  CreditMemoLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    CreditMemoLineMod
  )],
  CreditMemoLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    OverrideItemAccountRef
    Other1
    Other2
  )],
  CreditMemoMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ClassRef
    ARAccountRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    CreditMemoLineMod
    CreditMemoLineGroupMod
  )],
  CreditMemoModRq => [qw(
    CreditMemoMod
    IncludeRetElement
  )],
  CreditMemoQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  CurrencyAdd => [qw(
    Name
    IsActive
    CurrencyCode
    CurrencyFormat
  )],
  CurrencyAddRq => [qw(
    CurrencyAdd
    IncludeRetElement
  )],
  CurrencyFilter => [qw(
    ListID
    FullName
  )],
  CurrencyFormat => [qw(
    ThousandSeparator
    ThousandSeparatorGrouping
    DecimalPlaces
    DecimalSeparator
  )],
  CurrencyMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    CurrencyCode
    CurrencyFormat
  )],
  CurrencyModRq => [qw(
    CurrencyMod
    IncludeRetElement
  )],
  CurrencyQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  CurrencyRef => [qw(
    ListID
    FullName
  )],
  CustomDetailReportQueryRq => [qw(
    CustomDetailReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeRowsBy
    IncludeColumn
    IncludeAccounts
    ReportOpenBalanceAsOf
    ReportBasis
  )],
  CustomSummaryReportQueryRq => [qw(
    CustomSummaryReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeColumnsBy
    SummarizeRowsBy
    IncludeSubcolumns
    ReportCalendar
    ReturnRows
    ReturnColumns
    ReportBasis
  )],
  CustomerAdd => [qw(
    Name
    IsActive
    ParentRef
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    BillAddress
    ShipAddress
    PrintAs
    Phone
    Mobile
    Pager
    AltPhone
    Fax
    Email
    Contact
    AltContact
    CustomerTypeRef
    TermsRef
    SalesRepRef
    OpenBalance
    OpenBalanceDate
    SalesTaxCodeRef
    ItemSalesTaxRef
    SalesTaxCountry
    ResaleNumber
    AccountNumber
    CreditLimit
    PreferredPaymentMethodRef
    CreditCardInfo
    JobStatus
    JobStartDate
    JobProjectedEndDate
    JobEndDate
    JobDesc
    JobTypeRef
    Notes
    IsStatementWithParent
    DeliveryMethod
    PriceLevelRef
    ExternalGUID
    TaxRegistrationNumber
    CurrencyRef
  )],
  CustomerAddRq => [qw(
    CustomerAdd
    IncludeRetElement
  )],
  CustomerMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    BillAddress
    ShipAddress
    PrintAs
    Phone
    Mobile
    Pager
    AltPhone
    Fax
    Email
    Contact
    AltContact
    CustomerTypeRef
    TermsRef
    SalesRepRef
    SalesTaxCodeRef
    ItemSalesTaxRef
    SalesTaxCountry
    ResaleNumber
    AccountNumber
    CreditLimit
    PreferredPaymentMethodRef
    CreditCardInfo
    JobStatus
    JobStartDate
    JobProjectedEndDate
    JobEndDate
    JobDesc
    JobTypeRef
    Notes
    IsStatementWithParent
    DeliveryMethod
    PriceLevelRef
    TaxRegistrationNumber
    CurrencyRef
  )],
  CustomerModRq => [qw(
    CustomerMod
    IncludeRetElement
  )],
  CustomerMsgAdd => [qw(
    Name
    IsActive
  )],
  CustomerMsgAddRq => [qw(
    CustomerMsgAdd
    IncludeRetElement
  )],
  CustomerMsgQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  CustomerMsgRef => [qw(
    ListID
    FullName
  )],
  CustomerQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    TotalBalanceFilter
    CurrencyFilter
    IncludeRetElement
    OwnerID
  )],
  CustomerRef => [qw(
    ListID
    FullName
  )],
  CustomerSalesTaxCodeRef => [qw(
    ListID
    FullName
  )],
  CustomerTypeAdd => [qw(
    Name
    IsActive
    ParentRef
  )],
  CustomerTypeAddRq => [qw(
    CustomerTypeAdd
    IncludeRetElement
  )],
  CustomerTypeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  CustomerTypeRef => [qw(
    ListID
    FullName
  )],
  DataEventRecoveryInfoDelRq => [qw(
    SubscriberID
  )],
  DataEventRecoveryInfoQueryRq => [qw(
    SubscriberID
  )],
  DataEventSubscriptionAdd => [qw(
    SubscriberID
    COMCallbackInfo
    DeliveryPolicy
    TrackLostEvents
    DeliverOwnEvents
    ListEventSubscription
    TxnEventSubscription
  )],
  DataEventSubscriptionAddRq => [qw(
    DataEventSubscriptionAdd
  )],
  DataEventSubscriptionQueryRq => [qw(
    SubscriberID
  )],
  DataExt => [qw(
    OwnerID
    DataExtName
    DataExtValue
  )],
  DataExtAdd => [qw(
    OwnerID
    DataExtName
    ListDataExtType
    ListObjRef
    TxnDataExtType
    TxnID
    TxnLineID
    OtherDataExtType
    DataExtValue
  )],
  DataExtAddRq => [qw(
    DataExtAdd
  )],
  DataExtDefAdd => [qw(
    OwnerID
    DataExtName
    DataExtType
    AssignToObject
  )],
  DataExtDefAddRq => [qw(
    DataExtDefAdd
    IncludeRetElement
  )],
  DataExtDefDelRq => [qw(
    OwnerID
    DataExtName
  )],
  DataExtDefMod => [qw(
    OwnerID
    DataExtName
    DataExtNewName
    AssignToObject
    RemoveFromObject
  )],
  DataExtDefModRq => [qw(
    DataExtDefMod
    IncludeRetElement
  )],
  DataExtDefQueryRq => [qw(
    OwnerID
    AssignToObject
    IncludeRetElement
  )],
  DataExtDel => [qw(
    OwnerID
    DataExtName
    ListDataExtType
    ListObjRef
    TxnDataExtType
    TxnID
    TxnLineID
    OtherDataExtType
  )],
  DataExtDelRq => [qw(
    DataExtDel
  )],
  DataExtMod => [qw(
    OwnerID
    DataExtName
    ListDataExtType
    ListObjRef
    TxnDataExtType
    TxnID
    TxnLineID
    OtherDataExtType
    DataExtValue
  )],
  DataExtModRq => [qw(
    DataExtMod
  )],
  DateDrivenTermsAdd => [qw(
    Name
    IsActive
    DayOfMonthDue
    DueNextMonthDays
    DiscountDayOfMonth
    DiscountPct
  )],
  DateDrivenTermsAddRq => [qw(
    DateDrivenTermsAdd
    IncludeRetElement
  )],
  DateDrivenTermsQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  DefaultUnit => [qw(
    UnitUsedFor
    Unit
  )],
  DeletedDateRangeFilter => [qw(
    FromDeletedDate
    ToDeletedDate
  )],
  DepositAdd => [qw(
    TxnDate
    DepositToAccountRef
    Memo
    CashBackInfoAdd
    CurrencyRef
    ExchangeRate
    DepositLineAdd
  )],
  DepositAddRq => [qw(
    DepositAdd
    IncludeRetElement
  )],
  DepositLineAdd => [qw(
    PaymentTxnID
    PaymentTxnLineID
    OverrideMemo
    OverrideCheckNumber
    OverrideClassRef
    EntityRef
    AccountRef
    Memo
    CheckNumber
    PaymentMethodRef
    ClassRef
    Amount
  )],
  DepositLineMod => [qw(
    TxnLineID
    PaymentTxnID
    PaymentTxnLineID
    OverrideMemo
    OverrideCheckNumber
    OverrideClassRef
    EntityRef
    AccountRef
    Memo
    CheckNumber
    PaymentMethodRef
    ClassRef
    Amount
  )],
  DepositMod => [qw(
    TxnID
    EditSequence
    TxnDate
    DepositToAccountRef
    Memo
    CashBackInfoMod
    CurrencyRef
    ExchangeRate
    DepositLineMod
  )],
  DepositModRq => [qw(
    DepositMod
    IncludeRetElement
  )],
  DepositQueryRq => [qw(
    TxnID
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  DepositToAccountRef => [qw(
    ListID
    FullName
  )],
  DiscountAccountRef => [qw(
    ListID
    FullName
  )],
  DiscountLineAdd => [qw(
    Amount
    RatePercent
    IsTaxable
    AccountRef
  )],
  DisplayCondition => [qw(
    VisibleIf
    VisibleIfNot
    EnabledIf
    EnabledIfNot
  )],
  Earnings => [qw(
    PayrollItemWageRef
    Rate
    RatePercent
  )],
  EmployeeAdd => [qw(
    Name
    IsActive
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    EmployeeAddress
    PrintAs
    Phone
    Mobile
    Pager
    PagerPIN
    AltPhone
    Fax
    SSN
    Email
    EmployeeType
    Gender
    HiredDate
    ReleasedDate
    BirthDate
    AccountNumber
    Notes
    BillingRateRef
    EmployeePayrollInfo
    ExternalGUID
  )],
  EmployeeAddRq => [qw(
    EmployeeAdd
    IncludeRetElement
  )],
  EmployeeAddress => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    City
    State
    PostalCode
    Country
  )],
  EmployeeMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    EmployeeAddress
    PrintAs
    Phone
    Mobile
    Pager
    PagerPIN
    AltPhone
    Fax
    Email
    BirthDate
    AccountNumber
    Notes
    BillingRateRef
    EmployeePayrollInfoMod
  )],
  EmployeeModRq => [qw(
    EmployeeMod
    IncludeRetElement
  )],
  EmployeePayrollInfo => [qw(
    PayPeriod
    ClassRef
    ClearEarnings
    Earnings
    UseTimeDataToCreatePaychecks
    SickHours
    VacationHours
  )],
  EmployeePayrollInfoMod => [qw(
    PayPeriod
    ClassRef
    ClearEarnings
    Earnings
    UseTimeDataToCreatePaychecks
    SickHours
    VacationHours
  )],
  EmployeeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  EntityFilter => [qw(
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  EntityQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  EntityRef => [qw(
    ListID
    FullName
  )],
  EstimateAdd => [qw(
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsActive
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    EstimateLineAdd
    EstimateLineGroupAdd
  )],
  EstimateAddRq => [qw(
    EstimateAdd
    IncludeRetElement
  )],
  EstimateLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Rate
    RatePercent
    ClassRef
    Amount
    TaxAmount
    SalesTaxCodeRef
    MarkupRate
    MarkupRatePercent
    PriceLevelRef
    OverrideItemAccountRef
    Other1
    Other2
    DataExt
  )],
  EstimateLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    DataExt
  )],
  EstimateLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    EstimateLineMod
  )],
  EstimateLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    RatePercent
    ClassRef
    Amount
    TaxAmount
    SalesTaxCodeRef
    MarkupRate
    MarkupRatePercent
    PriceLevelRef
    Other1
    Other2
  )],
  EstimateMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsActive
    CreateChangeOrder
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    EstimateLineMod
    EstimateLineGroupMod
  )],
  EstimateModRq => [qw(
    EstimateMod
    IncludeRetElement
  )],
  EstimateQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  ExpenseAccountRef => [qw(
    ListID
    FullName
  )],
  ExpenseLineAdd => [qw(
    AccountRef
    Amount
    TaxAmount
    Memo
    CustomerRef
    ClassRef
    SalesTaxCodeRef
    BillableStatus
  )],
  ExpenseLineMod => [qw(
    TxnLineID
    AccountRef
    Amount
    TaxAmount
    Memo
    CustomerRef
    ClassRef
    SalesTaxCodeRef
    BillableStatus
  )],
  FixedAssetSalesInfo => [qw(
    SalesDesc
    SalesDate
    SalesPrice
    SalesExpense
  )],
  FixedAssetSalesInfoMod => [qw(
    SalesDesc
    SalesDate
    SalesPrice
    SalesExpense
  )],
  Form1099CategoryAccountMappingMod => [qw(
    IsFiling1099Misc
    CategoryAccountMappingMod
  )],
  Form1099CategoryAccountMappingModRq => [qw(
    Form1099CategoryAccountMappingMod
  )],
  Form1099CategoryAccountMappingQueryRq => [qw(
    MappingCategory
  )],
  GeneralDetailReportQueryRq => [qw(
    GeneralDetailReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeRowsBy
    IncludeColumn
    IncludeAccounts
    ReportOpenBalanceAsOf
    ReportBasis
  )],
  GeneralSummaryReportQueryRq => [qw(
    GeneralSummaryReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeColumnsBy
    IncludeSubcolumns
    ReportCalendar
    ReturnRows
    ReturnColumns
    ReportBasis
  )],
  HostQueryRq => [qw(
    IncludeListMetaData
    IncludeRetElement
  )],
  IncludeListMetaData => [qw(
    IncludeMaxCapacity
  )],
  IncomeAccountRef => [qw(
    ListID
    FullName
  )],
  InventoryAdjustmentAdd => [qw(
    AccountRef
    TxnDate
    RefNumber
    CustomerRef
    ClassRef
    Memo
    InventoryAdjustmentLineAdd
  )],
  InventoryAdjustmentAddRq => [qw(
    InventoryAdjustmentAdd
    IncludeRetElement
  )],
  InventoryAdjustmentLineAdd => [qw(
    ItemRef
    QuantityAdjustment
    ValueAdjustment
  )],
  InventoryAdjustmentQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    ItemFilter
    RefNumberFilter
    RefNumberRangeFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  InvoiceAdd => [qw(
    CustomerRef
    ClassRef
    ARAccountRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    IsFinanceCharge
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    LinkToTxnID
    InvoiceLineAdd
    InvoiceLineGroupAdd
    DiscountLineAdd
    SalesTaxLineAdd
    ShippingLineAdd
  )],
  InvoiceAddRq => [qw(
    InvoiceAdd
    IncludeRetElement
  )],
  InvoiceLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    IsTaxable
    OverrideItemAccountRef
    Other1
    Other2
    LinkToTxn
    DataExt
  )],
  InvoiceLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    ServiceDate
    DataExt
  )],
  InvoiceLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    InvoiceLineMod
  )],
  InvoiceLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    OverrideItemAccountRef
    Other1
    Other2
  )],
  InvoiceMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ClassRef
    ARAccountRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    InvoiceLineMod
    InvoiceLineGroupMod
  )],
  InvoiceModRq => [qw(
    InvoiceMod
    IncludeRetElement
  )],
  InvoiceQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    PaidStatus
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  ItemAssembliesCanBuildQueryRq => [qw(
    ItemInventoryAssemblyRef
    TxnDate
  )],
  ItemDiscountAdd => [qw(
    Name
    IsActive
    ParentRef
    ItemDesc
    SalesTaxCodeRef
    DiscountRate
    DiscountRatePercent
    AccountRef
    ExternalGUID
  )],
  ItemDiscountAddRq => [qw(
    ItemDiscountAdd
    IncludeRetElement
  )],
  ItemDiscountMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    ItemDesc
    SalesTaxCodeRef
    DiscountRate
    DiscountRatePercent
    AccountRef
    ApplyAccountRefToExistingTxns
  )],
  ItemDiscountModRq => [qw(
    ItemDiscountMod
    IncludeRetElement
  )],
  ItemDiscountQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemFilter => [qw(
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  ItemFixedAssetAdd => [qw(
    Name
    IsActive
    AcquiredAs
    PurchaseDesc
    PurchaseDate
    PurchaseCost
    VendorOrPayeeName
    AssetAccountRef
    FixedAssetSalesInfo
    AssetDesc
    Location
    PONumber
    SerialNumber
    WarrantyExpDate
    Notes
    AssetNumber
    CostBasis
    YearEndAccumulatedDepreciation
    YearEndBookValue
    ExternalGUID
  )],
  ItemFixedAssetAddRq => [qw(
    ItemFixedAssetAdd
    IncludeRetElement
  )],
  ItemFixedAssetMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    AcquiredAs
    PurchaseDesc
    PurchaseDate
    PurchaseCost
    VendorOrPayeeName
    AssetAccountRef
    FixedAssetSalesInfoMod
    AssetDesc
    Location
    PONumber
    SerialNumber
    WarrantyExpDate
    Notes
    AssetNumber
    CostBasis
    YearEndAccumulatedDepreciation
    YearEndBookValue
  )],
  ItemFixedAssetModRq => [qw(
    ItemFixedAssetMod
    IncludeRetElement
  )],
  ItemFixedAssetQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemGroupAdd => [qw(
    Name
    IsActive
    ItemDesc
    UnitOfMeasureSetRef
    IsPrintItemsInGroup
    ExternalGUID
    ItemGroupLine
  )],
  ItemGroupAddRq => [qw(
    ItemGroupAdd
    IncludeRetElement
  )],
  ItemGroupLine => [qw(
    ItemRef
    Quantity
    UnitOfMeasure
  )],
  ItemGroupLineAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
  )],
  ItemGroupLineMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    ItemLineMod
  )],
  ItemGroupMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ItemDesc
    UnitOfMeasureSetRef
    ForceUOMChange
    IsPrintItemsInGroup
    ClearItemsInGroup
    ItemGroupLine
  )],
  ItemGroupModRq => [qw(
    ItemGroupMod
    IncludeRetElement
  )],
  ItemGroupQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemGroupRef => [qw(
    ListID
    FullName
  )],
  ItemInventoryAdd => [qw(
    Name
    IsActive
    ParentRef
    ManufacturerPartNumber
    UnitOfMeasureSetRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesDesc
    SalesPrice
    IncomeAccountRef
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    COGSAccountRef
    PrefVendorRef
    AssetAccountRef
    ReorderPoint
    QuantityOnHand
    TotalValue
    InventoryDate
    ExternalGUID
  )],
  ItemInventoryAddRq => [qw(
    ItemInventoryAdd
    IncludeRetElement
  )],
  ItemInventoryAssemblyAdd => [qw(
    Name
    IsActive
    ParentRef
    UnitOfMeasureSetRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesDesc
    SalesPrice
    IncomeAccountRef
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    COGSAccountRef
    PrefVendorRef
    AssetAccountRef
    BuildPoint
    QuantityOnHand
    TotalValue
    InventoryDate
    ExternalGUID
    ItemInventoryAssemblyLine
  )],
  ItemInventoryAssemblyAddRq => [qw(
    ItemInventoryAssemblyAdd
    IncludeRetElement
  )],
  ItemInventoryAssemblyLine => [qw(
    ItemInventoryRef
    Quantity
  )],
  ItemInventoryAssemblyMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    UnitOfMeasureSetRef
    ForceUOMChange
    IsTaxIncluded
    SalesTaxCodeRef
    SalesDesc
    SalesPrice
    IncomeAccountRef
    ApplyIncomeAccountRefToExistingTxns
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    COGSAccountRef
    PrefVendorRef
    AssetAccountRef
    BuildPoint
    ClearItemsInGroup
    ItemInventoryAssemblyLine
  )],
  ItemInventoryAssemblyModRq => [qw(
    ItemInventoryAssemblyMod
    IncludeRetElement
  )],
  ItemInventoryAssemblyQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemInventoryAssemblyRef => [qw(
    ListID
    FullName
  )],
  ItemInventoryMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    ManufacturerPartNumber
    UnitOfMeasureSetRef
    ForceUOMChange
    IsTaxIncluded
    SalesTaxCodeRef
    SalesDesc
    SalesPrice
    IncomeAccountRef
    ApplyIncomeAccountRefToExistingTxns
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    COGSAccountRef
    ApplyCOGSAccountRefToExistingTxns
    PrefVendorRef
    AssetAccountRef
    ReorderPoint
  )],
  ItemInventoryModRq => [qw(
    ItemInventoryMod
    IncludeRetElement
  )],
  ItemInventoryQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemInventoryRef => [qw(
    ListID
    FullName
  )],
  ItemLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Cost
    Amount
    TaxAmount
    CustomerRef
    ClassRef
    SalesTaxCodeRef
    BillableStatus
    OverrideItemAccountRef
    LinkToTxn
  )],
  ItemLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Cost
    Amount
    TaxAmount
    CustomerRef
    ClassRef
    SalesTaxCodeRef
    BillableStatus
    OverrideItemAccountRef
  )],
  ItemNonInventoryAdd => [qw(
    Name
    IsActive
    ParentRef
    ManufacturerPartNumber
    UnitOfMeasureSetRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchase
    SalesAndPurchase
    ExternalGUID
  )],
  ItemNonInventoryAddRq => [qw(
    ItemNonInventoryAdd
    IncludeRetElement
  )],
  ItemNonInventoryMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    ManufacturerPartNumber
    UnitOfMeasureSetRef
    ForceUOMChange
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchaseMod
    SalesAndPurchaseMod
  )],
  ItemNonInventoryModRq => [qw(
    ItemNonInventoryMod
    IncludeRetElement
  )],
  ItemNonInventoryQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemOtherChargeAdd => [qw(
    Name
    IsActive
    ParentRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchase
    SalesAndPurchase
    ExternalGUID
  )],
  ItemOtherChargeAddRq => [qw(
    ItemOtherChargeAdd
    IncludeRetElement
  )],
  ItemOtherChargeMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchaseMod
    SalesAndPurchaseMod
  )],
  ItemOtherChargeModRq => [qw(
    ItemOtherChargeMod
    IncludeRetElement
  )],
  ItemOtherChargeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemPaymentAdd => [qw(
    Name
    IsActive
    ItemDesc
    DepositToAccountRef
    PaymentMethodRef
    ExternalGUID
  )],
  ItemPaymentAddRq => [qw(
    ItemPaymentAdd
    IncludeRetElement
  )],
  ItemPaymentMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ItemDesc
    DepositToAccountRef
    PaymentMethodRef
  )],
  ItemPaymentModRq => [qw(
    ItemPaymentMod
    IncludeRetElement
  )],
  ItemPaymentQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemPurchaseTaxRef => [qw(
    ListID
    FullName
  )],
  ItemQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemReceiptAdd => [qw(
    VendorRef
    APAccountRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    LinkToTxnID
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  ItemReceiptAddRq => [qw(
    ItemReceiptAdd
    IncludeRetElement
  )],
  ItemReceiptMod => [qw(
    TxnID
    EditSequence
    VendorRef
    APAccountRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  ItemReceiptModRq => [qw(
    ItemReceiptMod
    IncludeRetElement
  )],
  ItemReceiptQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  ItemRef => [qw(
    ListID
    FullName
  )],
  ItemSalesTaxAdd => [qw(
    Name
    IsActive
    ItemDesc
    TaxRate
    TaxVendorRef
    SalesTaxReturnLineRef
    ExternalGUID
  )],
  ItemSalesTaxAddRq => [qw(
    ItemSalesTaxAdd
    IncludeRetElement
  )],
  ItemSalesTaxGroupAdd => [qw(
    Name
    IsActive
    ItemDesc
    ExternalGUID
    ItemSalesTaxRef
  )],
  ItemSalesTaxGroupAddRq => [qw(
    ItemSalesTaxGroupAdd
    IncludeRetElement
  )],
  ItemSalesTaxGroupMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ItemDesc
    ItemSalesTaxRef
  )],
  ItemSalesTaxGroupModRq => [qw(
    ItemSalesTaxGroupMod
    IncludeRetElement
  )],
  ItemSalesTaxGroupQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemSalesTaxMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ItemDesc
    TaxRate
    TaxVendorRef
    SalesTaxReturnLineRef
  )],
  ItemSalesTaxModRq => [qw(
    ItemSalesTaxMod
    IncludeRetElement
  )],
  ItemSalesTaxQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemSalesTaxRef => [qw(
    ListID
    FullName
  )],
  ItemServiceAdd => [qw(
    Name
    IsActive
    ParentRef
    UnitOfMeasureSetRef
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchase
    SalesAndPurchase
    ExternalGUID
  )],
  ItemServiceAddRq => [qw(
    ItemServiceAdd
    IncludeRetElement
  )],
  ItemServiceMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ParentRef
    UnitOfMeasureSetRef
    ForceUOMChange
    IsTaxIncluded
    SalesTaxCodeRef
    SalesOrPurchaseMod
    SalesAndPurchaseMod
  )],
  ItemServiceModRq => [qw(
    ItemServiceMod
    IncludeRetElement
  )],
  ItemServiceQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  ItemServiceRef => [qw(
    ListID
    FullName
  )],
  ItemSubtotalAdd => [qw(
    Name
    IsActive
    ItemDesc
    ExternalGUID
  )],
  ItemSubtotalAddRq => [qw(
    ItemSubtotalAdd
    IncludeRetElement
  )],
  ItemSubtotalMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    ItemDesc
  )],
  ItemSubtotalModRq => [qw(
    ItemSubtotalMod
    IncludeRetElement
  )],
  ItemSubtotalQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  JobReportQueryRq => [qw(
    JobReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportTxnTypeFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeColumnsBy
    IncludeSubcolumns
  )],
  JobTypeAdd => [qw(
    Name
    IsActive
    ParentRef
  )],
  JobTypeAddRq => [qw(
    JobTypeAdd
    IncludeRetElement
  )],
  JobTypeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  JobTypeRef => [qw(
    ListID
    FullName
  )],
  JournalCreditLine => [qw(
    TxnLineID
    AccountRef
    Amount
    TaxAmount
    Memo
    EntityRef
    ClassRef
    ItemSalesTaxRef
    BillableStatus
  )],
  JournalDebitLine => [qw(
    TxnLineID
    AccountRef
    Amount
    TaxAmount
    Memo
    EntityRef
    ClassRef
    ItemSalesTaxRef
    BillableStatus
  )],
  JournalEntryAdd => [qw(
    TxnDate
    RefNumber
    Memo
    IsAdjustment
    IsHomeCurrencyAdjustment
    IsAmountsEnteredInHomeCurrency
    CurrencyRef
    ExchangeRate
    JournalDebitLine
    JournalCreditLine
  )],
  JournalEntryAddRq => [qw(
    JournalEntryAdd
    IncludeRetElement
  )],
  JournalEntryMod => [qw(
    TxnID
    EditSequence
    TxnDate
    RefNumber
    IsAdjustment
    IsAmountsEnteredInHomeCurrency
    CurrencyRef
    ExchangeRate
    JournalLineMod
  )],
  JournalEntryModRq => [qw(
    JournalEntryMod
    IncludeRetElement
  )],
  JournalEntryQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  JournalLineMod => [qw(
    TxnLineID
    JournalLineType
    AccountRef
    Amount
    TaxAmount
    Memo
    EntityRef
    ClassRef
    ItemSalesTaxRef
    BillableStatus
  )],
  LinkToTxn => [qw(
    TxnID
    TxnLineID
  )],
  ListDelRq => [qw(
    ListDelType
    ListID
  )],
  ListDeletedQueryRq => [qw(
    ListDelType
    DeletedDateRangeFilter
    IncludeRetElement
  )],
  ListDisplayAddRq => [qw(
    ListDisplayAddType
  )],
  ListDisplayModRq => [qw(
    ListDisplayModType
    ListID
  )],
  ListEventSubscription => [qw(
    ListEventType
    ListEventOperation
  )],
  ListMergeRq => [qw(
    ListMergeType
    MergeFrom
    MergeTo
    SameShipAddrOk
  )],
  ListObjRef => [qw(
    ListID
    FullName
  )],
  MappingAccount => [qw(
    AccountRef
    ForceMapping
  )],
  MenuExtensionSubscription => [qw(
    AddToMenu
    Submenu
    MenuItem
  )],
  MenuItem => [qw(
    MenuText
    EventTag
    DisplayCondition
  )],
  MergeFrom => [qw(
    ListID
    EditSequence
  )],
  MergeTo => [qw(
    ListID
    EditSequence
  )],
  ModifiedDateRangeFilter => [qw(
    FromModifiedDate
    ToModifiedDate
  )],
  NameFilter => [qw(
    MatchCriterion
    Name
  )],
  NameRangeFilter => [qw(
    FromName
    ToName
  )],
  OtherNameAdd => [qw(
    Name
    IsActive
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    OtherNameAddress
    Phone
    AltPhone
    Fax
    Email
    Contact
    AltContact
    AccountNumber
    Notes
    ExternalGUID
  )],
  OtherNameAddRq => [qw(
    OtherNameAdd
    IncludeRetElement
  )],
  OtherNameAddress => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    Addr5
    City
    State
    PostalCode
    Country
    Note
  )],
  OtherNameMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    OtherNameAddress
    Phone
    AltPhone
    Fax
    Email
    Contact
    AltContact
    AccountNumber
    Notes
  )],
  OtherNameModRq => [qw(
    OtherNameMod
    IncludeRetElement
  )],
  OtherNameQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
    OwnerID
  )],
  OverrideClassRef => [qw(
    ListID
    FullName
  )],
  OverrideItemAccountRef => [qw(
    ListID
    FullName
  )],
  OverrideUOMSetRef => [qw(
    ListID
    FullName
  )],
  ParentRef => [qw(
    ListID
    FullName
  )],
  PayeeEntityRef => [qw(
    ListID
    FullName
  )],
  PaymentMethodAdd => [qw(
    Name
    IsActive
    PaymentMethodType
  )],
  PaymentMethodAddRq => [qw(
    PaymentMethodAdd
    IncludeRetElement
  )],
  PaymentMethodQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    PaymentMethodType
    IncludeRetElement
  )],
  PaymentMethodRef => [qw(
    ListID
    FullName
  )],
  PayrollDetailReportQueryRq => [qw(
    PayrollDetailReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeRowsBy
    IncludeColumn
    IncludeAccounts
    ReportOpenBalanceAsOf
  )],
  PayrollItemNonWageQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  PayrollItemWageAdd => [qw(
    Name
    IsActive
    WageType
    ExpenseAccountRef
  )],
  PayrollItemWageAddRq => [qw(
    PayrollItemWageAdd
    IncludeRetElement
  )],
  PayrollItemWageQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  PayrollItemWageRef => [qw(
    ListID
    FullName
  )],
  PayrollSummaryReportQueryRq => [qw(
    PayrollSummaryReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportAccountFilter
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    ReportModifiedDateRangeFilter
    ReportModifiedDateRangeMacro
    ReportDetailLevelFilter
    ReportPostingStatusFilter
    SummarizeColumnsBy
    IncludeSubcolumns
    ReportCalendar
    ReturnRows
    ReturnColumns
  )],
  PrefVendorRef => [qw(
    ListID
    FullName
  )],
  PreferencesQueryRq => [qw(
    IncludeRetElement
  )],
  PreferredPaymentMethodRef => [qw(
    ListID
    FullName
  )],
  PrefillAccountRef => [qw(
    ListID
    FullName
  )],
  PriceLevelAdd => [qw(
    Name
    IsActive
    PriceLevelFixedPercentage
    PriceLevelPerItem
    CurrencyRef
  )],
  PriceLevelAddRq => [qw(
    PriceLevelAdd
    IncludeRetElement
  )],
  PriceLevelMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    PriceLevelFixedPercentage
    PriceLevelPerItem
    CurrencyRef
  )],
  PriceLevelModRq => [qw(
    PriceLevelMod
    IncludeRetElement
  )],
  PriceLevelPerItem => [qw(
    ItemRef
    CustomPrice
    CustomPricePercent
    AdjustPercentage
    AdjustRelativeTo
  )],
  PriceLevelQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    ItemRef
    CurrencyFilter
    IncludeRetElement
  )],
  PriceLevelRef => [qw(
    ListID
    FullName
  )],
  PurchaseOrderAdd => [qw(
    VendorRef
    ClassRef
    ShipToEntityRef
    TemplateRef
    TxnDate
    RefNumber
    VendorAddress
    ShipAddress
    TermsRef
    DueDate
    ExpectedDate
    ShipMethodRef
    FOB
    Memo
    VendorMsg
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    SalesTaxCodeRef
    Other1
    Other2
    ExchangeRate
    PurchaseOrderLineAdd
    PurchaseOrderLineGroupAdd
  )],
  PurchaseOrderAddRq => [qw(
    PurchaseOrderAdd
    IncludeRetElement
  )],
  PurchaseOrderLineAdd => [qw(
    ItemRef
    ManufacturerPartNumber
    Desc
    Quantity
    UnitOfMeasure
    Rate
    ClassRef
    Amount
    TaxAmount
    CustomerRef
    ServiceDate
    SalesTaxCodeRef
    OverrideItemAccountRef
    Other1
    Other2
    DataExt
  )],
  PurchaseOrderLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    ServiceDate
    DataExt
  )],
  PurchaseOrderLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    PurchaseOrderLineMod
  )],
  PurchaseOrderLineMod => [qw(
    TxnLineID
    ItemRef
    ManufacturerPartNumber
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    ClassRef
    Amount
    TaxAmount
    CustomerRef
    ServiceDate
    SalesTaxCodeRef
    IsManuallyClosed
    OverrideItemAccountRef
    Other1
    Other2
  )],
  PurchaseOrderMod => [qw(
    TxnID
    EditSequence
    VendorRef
    ClassRef
    ShipToEntityRef
    TemplateRef
    TxnDate
    RefNumber
    VendorAddress
    ShipAddress
    TermsRef
    DueDate
    ExpectedDate
    ShipMethodRef
    FOB
    IsManuallyClosed
    Memo
    VendorMsg
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    SalesTaxCodeRef
    Other1
    Other2
    ExchangeRate
    PurchaseOrderLineMod
    PurchaseOrderLineGroupMod
  )],
  PurchaseOrderModRq => [qw(
    PurchaseOrderMod
    IncludeRetElement
  )],
  PurchaseOrderQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  PurchaseTaxCodeRef => [qw(
    ListID
    FullName
  )],
  QBXML => [qw(
    SignonMsgsRq
    QBXMLMsgsRq
    QBXMLSubscriptionMsgsRq
  )],
  QBXMLSubscriptionMsgsRq => [qw(
    DataEventSubscriptionAddRq
    DataEventSubscriptionQueryRq
    UIEventSubscriptionAddRq
    UIEventSubscriptionQueryRq
    UIExtensionSubscriptionAddRq
    UIExtensionSubscriptionQueryRq
    SubscriptionDelRq
  )],
  QuantityAdjustment => [qw(
    NewQuantity
    QuantityDifference
  )],
  RateEntry => [qw(
    Rate
    EffectiveDate
  )],
  ReceivePaymentAdd => [qw(
    CustomerRef
    ARAccountRef
    TxnDate
    RefNumber
    TotalAmount
    ExchangeRate
    PaymentMethodRef
    Memo
    DepositToAccountRef
    CreditCardTxnInfo
    IsAutoApply
    AppliedToTxnAdd
  )],
  ReceivePaymentAddRq => [qw(
    ReceivePaymentAdd
    IncludeRetElement
  )],
  ReceivePaymentMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ARAccountRef
    TxnDate
    RefNumber
    TotalAmount
    ExchangeRate
    PaymentMethodRef
    Memo
    DepositToAccountRef
    CreditCardTxnInfoMod
    AppliedToTxnMod
  )],
  ReceivePaymentModRq => [qw(
    ReceivePaymentMod
    IncludeRetElement
  )],
  ReceivePaymentQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  ReceivePaymentToDepositQueryRq => [qw(
    IncludeRetElement
  )],
  RefNumberFilter => [qw(
    MatchCriterion
    RefNumber
  )],
  RefNumberRangeFilter => [qw(
    FromRefNumber
    ToRefNumber
  )],
  RefundAppliedToTxnAdd => [qw(
    TxnID
    RefundAmount
  )],
  RefundFromAccountRef => [qw(
    ListID
    FullName
  )],
  RelatedUnit => [qw(
    Name
    Abbreviation
    ConversionRatio
  )],
  ReportAccountFilter => [qw(
    AccountTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  ReportClassFilter => [qw(
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  ReportEntityFilter => [qw(
    EntityTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  ReportItemFilter => [qw(
    ItemTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  ReportModifiedDateRangeFilter => [qw(
    FromReportModifiedDate
    ToReportModifiedDate
  )],
  ReportPeriod => [qw(
    FromReportDate
    ToReportDate
  )],
  ReportTxnTypeFilter => [qw(
    TxnTypeFilter
  )],
  SalesAndPurchase => [qw(
    SalesDesc
    SalesPrice
    IncomeAccountRef
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    ExpenseAccountRef
    PrefVendorRef
  )],
  SalesAndPurchaseMod => [qw(
    SalesDesc
    SalesPrice
    IncomeAccountRef
    ApplyIncomeAccountRefToExistingTxns
    PurchaseDesc
    PurchaseCost
    PurchaseTaxCodeRef
    ExpenseAccountRef
    ApplyExpenseAccountRefToExistingTxns
    PrefVendorRef
  )],
  SalesOrPurchase => [qw(
    Desc
    Price
    PricePercent
    AccountRef
  )],
  SalesOrPurchaseMod => [qw(
    Desc
    Price
    PricePercent
    AccountRef
    ApplyAccountRefToExistingTxns
  )],
  SalesOrderAdd => [qw(
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    IsManuallyClosed
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    SalesOrderLineAdd
    SalesOrderLineGroupAdd
  )],
  SalesOrderAddRq => [qw(
    SalesOrderAdd
    IncludeRetElement
  )],
  SalesOrderLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    SalesTaxCodeRef
    IsManuallyClosed
    Other1
    Other2
    DataExt
  )],
  SalesOrderLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    DataExt
  )],
  SalesOrderLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    SalesOrderLineMod
  )],
  SalesOrderLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    SalesTaxCodeRef
    IsManuallyClosed
    Other1
    Other2
  )],
  SalesOrderMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    PONumber
    TermsRef
    DueDate
    SalesRepRef
    FOB
    ShipDate
    ShipMethodRef
    ItemSalesTaxRef
    IsManuallyClosed
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    Other
    ExchangeRate
    SalesOrderLineMod
    SalesOrderLineGroupMod
  )],
  SalesOrderModRq => [qw(
    SalesOrderMod
    IncludeRetElement
  )],
  SalesOrderQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  SalesReceiptAdd => [qw(
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    CheckNumber
    PaymentMethodRef
    DueDate
    SalesRepRef
    ShipDate
    ShipMethodRef
    FOB
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    DepositToAccountRef
    CreditCardTxnInfo
    Other
    ExchangeRate
    SalesReceiptLineAdd
    SalesReceiptLineGroupAdd
    DiscountLineAdd
    SalesTaxLineAdd
    ShippingLineAdd
  )],
  SalesReceiptAddRq => [qw(
    SalesReceiptAdd
    IncludeRetElement
  )],
  SalesReceiptLineAdd => [qw(
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    IsTaxable
    OverrideItemAccountRef
    Other1
    Other2
    CreditCardTxnInfo
    DataExt
  )],
  SalesReceiptLineGroupAdd => [qw(
    ItemGroupRef
    Desc
    Quantity
    UnitOfMeasure
    ServiceDate
    DataExt
  )],
  SalesReceiptLineGroupMod => [qw(
    TxnLineID
    ItemGroupRef
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    SalesReceiptLineMod
  )],
  SalesReceiptLineMod => [qw(
    TxnLineID
    ItemRef
    Desc
    Quantity
    UnitOfMeasure
    OverrideUOMSetRef
    Rate
    RatePercent
    PriceLevelRef
    ClassRef
    Amount
    TaxAmount
    ServiceDate
    SalesTaxCodeRef
    OverrideItemAccountRef
    Other1
    Other2
  )],
  SalesReceiptMod => [qw(
    TxnID
    EditSequence
    CustomerRef
    ClassRef
    TemplateRef
    TxnDate
    RefNumber
    BillAddress
    ShipAddress
    IsPending
    CheckNumber
    PaymentMethodRef
    DueDate
    SalesRepRef
    ShipDate
    ShipMethodRef
    FOB
    ItemSalesTaxRef
    Memo
    CustomerMsgRef
    IsToBePrinted
    IsToBeEmailed
    IsTaxIncluded
    CustomerSalesTaxCodeRef
    DepositToAccountRef
    Other
    ExchangeRate
    SalesReceiptLineMod
    SalesReceiptLineGroupMod
  )],
  SalesReceiptModRq => [qw(
    SalesReceiptMod
    IncludeRetElement
  )],
  SalesReceiptQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  SalesRepAdd => [qw(
    Initial
    IsActive
    SalesRepEntityRef
  )],
  SalesRepAddRq => [qw(
    SalesRepAdd
    IncludeRetElement
  )],
  SalesRepEntityRef => [qw(
    ListID
    FullName
  )],
  SalesRepMod => [qw(
    ListID
    EditSequence
    Initial
    IsActive
    SalesRepEntityRef
  )],
  SalesRepModRq => [qw(
    SalesRepMod
    IncludeRetElement
  )],
  SalesRepQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  SalesRepRef => [qw(
    ListID
    FullName
  )],
  SalesTaxCodeAdd => [qw(
    Name
    IsActive
    IsTaxable
    Desc
    ItemPurchaseTaxRef
    ItemSalesTaxRef
  )],
  SalesTaxCodeAddRq => [qw(
    SalesTaxCodeAdd
    IncludeRetElement
  )],
  SalesTaxCodeMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    IsTaxable
    Desc
    ItemPurchaseTaxRef
    ItemSalesTaxRef
  )],
  SalesTaxCodeModRq => [qw(
    SalesTaxCodeMod
    IncludeRetElement
  )],
  SalesTaxCodeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  SalesTaxCodeRef => [qw(
    ListID
    FullName
  )],
  SalesTaxLineAdd => [qw(
    Amount
    RatePercent
    AccountRef
  )],
  SalesTaxPaymentCheckQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    ItemFilter
    RefNumberFilter
    RefNumberRangeFilter
    IncludeLineItems
    IncludeRetElement
    OwnerID
  )],
  SalesTaxReturnLineQueryRq => [qw(
    TaxAgencyVendorRef
  )],
  SalesTaxReturnLineRef => [qw(
    ListID
    FullName
  )],
  SalesTaxReturnRef => [qw(
    ListID
    FullName
  )],
  SetCredit => [qw(
    CreditTxnID
    TxnLineID
    AppliedAmount
  )],
  ShipAddress => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    Addr5
    City
    State
    PostalCode
    Country
    Note
  )],
  ShipMethodAdd => [qw(
    Name
    IsActive
  )],
  ShipMethodAddRq => [qw(
    ShipMethodAdd
    IncludeRetElement
  )],
  ShipMethodQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  ShipMethodRef => [qw(
    ListID
    FullName
  )],
  ShipToEntityRef => [qw(
    ListID
    FullName
  )],
  ShippingLineAdd => [qw(
    Amount
    AccountRef
  )],
  SickHours => [qw(
    HoursAvailable
    AccrualPeriod
    HoursAccrued
    MaximumHours
    IsResettingHoursEachNewYear
    HoursUsed
    AccrualStartDate
  )],
  SignonAppCertRq => [qw(
    ClientDateTime
    ApplicationLogin
    ConnectionTicket
    InstallationID
    Language
    AppID
    AppVer
  )],
  SignonDesktopRq => [qw(
    ClientDateTime
    ApplicationLogin
    ConnectionTicket
    InstallationID
    Language
    AppID
    AppVer
  )],
  SignonMsgsRq => [qw(
    SignonAppCertRq
    SignonDesktopRq
    SignonTicketRq
  )],
  SignonTicketRq => [qw(
    ClientDateTime
    SessionTicket
    AuthID
    InstallationID
    Language
    AppID
    AppVer
  )],
  SpecialAccountAdd => [qw(
    SpecialAccountType
    CurrencyRef
  )],
  SpecialAccountAddRq => [qw(
    SpecialAccountAdd
    IncludeRetElement
  )],
  SpecialItemAdd => [qw(
    SpecialItemType
    ExternalGUID
  )],
  SpecialItemAddRq => [qw(
    SpecialItemAdd
    IncludeRetElement
  )],
  StandardTermsAdd => [qw(
    Name
    IsActive
    StdDueDays
    StdDiscountDays
    DiscountPct
  )],
  StandardTermsAddRq => [qw(
    StandardTermsAdd
    IncludeRetElement
  )],
  StandardTermsQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  Submenu => [qw(
    DisplayCondition
    MenuItem
  )],
  SubscriptionDelRq => [qw(
    SubscriberID
    SubscriptionType
  )],
  TaxAgencyVendorRef => [qw(
    ListID
    FullName
  )],
  TaxOnPurchasesAccountRef => [qw(
    ListID
    FullName
  )],
  TaxOnSalesAccountRef => [qw(
    ListID
    FullName
  )],
  TaxVendorRef => [qw(
    ListID
    FullName
  )],
  TemplateQueryRq => [qw(
    IncludeRetElement
  )],
  TemplateRef => [qw(
    ListID
    FullName
  )],
  TermsQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  TermsRef => [qw(
    ListID
    FullName
  )],
  TimeReportQueryRq => [qw(
    TimeReportType
    DisplayReport
    ReportPeriod
    ReportDateMacro
    ReportEntityFilter
    ReportItemFilter
    ReportClassFilter
    SummarizeColumnsBy
    IncludeSubcolumns
    ReportCalendar
    ReturnRows
    ReturnColumns
  )],
  TimeTrackingAdd => [qw(
    TxnDate
    EntityRef
    CustomerRef
    ItemServiceRef
    Rate
    Duration
    ClassRef
    PayrollItemWageRef
    Notes
    BillableStatus
  )],
  TimeTrackingAddRq => [qw(
    TimeTrackingAdd
    IncludeRetElement
  )],
  TimeTrackingEntityFilter => [qw(
    ListID
    FullName
  )],
  TimeTrackingMod => [qw(
    TxnID
    EditSequence
    TxnDate
    EntityRef
    CustomerRef
    ItemServiceRef
    Rate
    Duration
    ClassRef
    PayrollItemWageRef
    Notes
    BillableStatus
  )],
  TimeTrackingModRq => [qw(
    TimeTrackingMod
    IncludeRetElement
  )],
  TimeTrackingQueryRq => [qw(
    TxnID
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    TimeTrackingEntityFilter
    IncludeRetElement
  )],
  ToDoAdd => [qw(
    Notes
    IsActive
    IsDone
    ReminderDate
  )],
  ToDoAddRq => [qw(
    ToDoAdd
    IncludeRetElement
  )],
  ToDoQueryRq => [qw(
    ListID
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    DoneStatus
    IncludeRetElement
  )],
  TotalBalanceFilter => [qw(
    Operator
    Amount
  )],
  TransactionAccountFilter => [qw(
    AccountTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  TransactionClassFilter => [qw(
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  TransactionDateRangeFilter => [qw(
    FromTxnDate
    ToTxnDate
    DateMacro
  )],
  TransactionEntityFilter => [qw(
    EntityTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  TransactionItemFilter => [qw(
    ItemTypeFilter
    ListID
    FullName
    ListIDWithChildren
    FullNameWithChildren
  )],
  TransactionModifiedDateRangeFilter => [qw(
    FromModifiedDate
    ToModifiedDate
    DateMacro
  )],
  TransactionQueryRq => [qw(
    TxnID
    MaxReturned
    RefNumber
    RefNumberCaseSensitive
    RefNumberFilter
    RefNumberRangeFilter
    TransactionModifiedDateRangeFilter
    TransactionDateRangeFilter
    TransactionEntityFilter
    TransactionAccountFilter
    TransactionItemFilter
    TransactionClassFilter
    TransactionTypeFilter
    TransactionDetailLevelFilter
    TransactionPostingStatusFilter
    TransactionPaidStatusFilter
    CurrencyFilter
    IncludeRetElement
  )],
  TransactionTypeFilter => [qw(
    TxnTypeFilter
  )],
  TxnDateRangeFilter => [qw(
    FromTxnDate
    ToTxnDate
    DateMacro
  )],
  TxnDelRq => [qw(
    TxnDelType
    TxnID
  )],
  TxnDeletedQueryRq => [qw(
    TxnDelType
    DeletedDateRangeFilter
    IncludeRetElement
  )],
  TxnDisplayAddRq => [qw(
    TxnDisplayAddType
    EntityRef
  )],
  TxnDisplayModRq => [qw(
    TxnDisplayModType
    TxnID
  )],
  TxnEventSubscription => [qw(
    TxnEventType
    TxnEventOperation
  )],
  TxnLineDetail => [qw(
    TxnLineID
    Amount
  )],
  TxnVoidRq => [qw(
    TxnVoidType
    TxnID
  )],
  UIEventSubscriptionAdd => [qw(
    SubscriberID
    COMCallbackInfo
    DeliveryPolicy
    CompanyFileEventSubscription
  )],
  UIEventSubscriptionAddRq => [qw(
    UIEventSubscriptionAdd
  )],
  UIEventSubscriptionQueryRq => [qw(
    SubscriberID
  )],
  UIExtensionSubscriptionAdd => [qw(
    SubscriberID
    COMCallbackInfo
    MenuExtensionSubscription
  )],
  UIExtensionSubscriptionAddRq => [qw(
    UIExtensionSubscriptionAdd
  )],
  UIExtensionSubscriptionQueryRq => [qw(
    SubscriberID
  )],
  UnitOfMeasureSetAdd => [qw(
    Name
    IsActive
    UnitOfMeasureType
    BaseUnit
    RelatedUnit
    DefaultUnit
  )],
  UnitOfMeasureSetAddRq => [qw(
    UnitOfMeasureSetAdd
    IncludeRetElement
  )],
  UnitOfMeasureSetQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  UnitOfMeasureSetRef => [qw(
    ListID
    FullName
  )],
  VacationHours => [qw(
    HoursAvailable
    AccrualPeriod
    HoursAccrued
    MaximumHours
    IsResettingHoursEachNewYear
    HoursUsed
    AccrualStartDate
  )],
  ValueAdjustment => [qw(
    NewQuantity
    NewValue
  )],
  VehicleAdd => [qw(
    Name
    IsActive
    Desc
  )],
  VehicleAddRq => [qw(
    VehicleAdd
    IncludeRetElement
  )],
  VehicleMileageAdd => [qw(
    VehicleRef
    CustomerRef
    ItemRef
    ClassRef
    TripStartDate
    TripEndDate
    OdometerStart
    OdometerEnd
    TotalMiles
    Notes
    BillableStatus
  )],
  VehicleMileageAddRq => [qw(
    VehicleMileageAdd
    IncludeRetElement
  )],
  VehicleMileageQueryRq => [qw(
    TxnID
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    IncludeRetElement
  )],
  VehicleMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    Desc
  )],
  VehicleModRq => [qw(
    VehicleMod
    IncludeRetElement
  )],
  VehicleQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  VehicleRef => [qw(
    ListID
    FullName
  )],
  VendorAdd => [qw(
    Name
    IsActive
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    VendorAddress
    Phone
    Mobile
    Pager
    AltPhone
    Fax
    Email
    Contact
    AltContact
    NameOnCheck
    AccountNumber
    Notes
    VendorTypeRef
    TermsRef
    CreditLimit
    VendorTaxIdent
    IsVendorEligibleFor1099
    OpenBalance
    OpenBalanceDate
    BillingRateRef
    ExternalGUID
    SalesTaxCodeRef
    SalesTaxCountry
    IsSalesTaxAgency
    SalesTaxReturnRef
    TaxRegistrationNumber
    ReportingPeriod
    IsTaxTrackedOnPurchases
    TaxOnPurchasesAccountRef
    IsTaxTrackedOnSales
    TaxOnSalesAccountRef
    IsTaxOnTax
    PrefillAccountRef
    CurrencyRef
  )],
  VendorAddRq => [qw(
    VendorAdd
    IncludeRetElement
  )],
  VendorAddress => [qw(
    Addr1
    Addr2
    Addr3
    Addr4
    Addr5
    City
    State
    PostalCode
    Country
    Note
  )],
  VendorCreditAdd => [qw(
    VendorRef
    APAccountRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ExpenseLineAdd
    ItemLineAdd
    ItemGroupLineAdd
  )],
  VendorCreditAddRq => [qw(
    VendorCreditAdd
    IncludeRetElement
  )],
  VendorCreditMod => [qw(
    TxnID
    EditSequence
    VendorRef
    APAccountRef
    TxnDate
    RefNumber
    Memo
    IsTaxIncluded
    SalesTaxCodeRef
    ExchangeRate
    ClearExpenseLines
    ExpenseLineMod
    ClearItemLines
    ItemLineMod
    ItemGroupLineMod
  )],
  VendorCreditModRq => [qw(
    VendorCreditMod
    IncludeRetElement
  )],
  VendorCreditQueryRq => [qw(
    TxnID
    RefNumber
    RefNumberCaseSensitive
    MaxReturned
    ModifiedDateRangeFilter
    TxnDateRangeFilter
    EntityFilter
    AccountFilter
    RefNumberFilter
    RefNumberRangeFilter
    CurrencyFilter
    IncludeLineItems
    IncludeLinkedTxns
    IncludeRetElement
    OwnerID
  )],
  VendorMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    CompanyName
    Salutation
    FirstName
    MiddleName
    LastName
    Suffix
    VendorAddress
    Phone
    Mobile
    Pager
    AltPhone
    Fax
    Email
    Contact
    AltContact
    NameOnCheck
    AccountNumber
    Notes
    VendorTypeRef
    TermsRef
    CreditLimit
    VendorTaxIdent
    IsVendorEligibleFor1099
    BillingRateRef
    SalesTaxCodeRef
    SalesTaxCountry
    IsSalesTaxAgency
    SalesTaxReturnRef
    TaxRegistrationNumber
    ReportingPeriod
    IsTaxTrackedOnPurchases
    TaxOnPurchasesAccountRef
    IsTaxTrackedOnSales
    TaxOnSalesAccountRef
    IsTaxOnTax
    PrefillAccountRef
    CurrencyRef
  )],
  VendorModRq => [qw(
    VendorMod
    IncludeRetElement
  )],
  VendorQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    TotalBalanceFilter
    CurrencyFilter
    IncludeRetElement
    OwnerID
  )],
  VendorRef => [qw(
    ListID
    FullName
  )],
  VendorTypeAdd => [qw(
    Name
    IsActive
    ParentRef
  )],
  VendorTypeAddRq => [qw(
    VendorTypeAdd
    IncludeRetElement
  )],
  VendorTypeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    IncludeRetElement
  )],
  VendorTypeRef => [qw(
    ListID
    FullName
  )],
  WorkersCompCodeAdd => [qw(
    Name
    IsActive
    Desc
    RateEntry
  )],
  WorkersCompCodeAddRq => [qw(
    WorkersCompCodeAdd
    IncludeRetElement
  )],
  WorkersCompCodeMod => [qw(
    ListID
    EditSequence
    Name
    IsActive
    Desc
    RateEntry
  )],
  WorkersCompCodeModRq => [qw(
    WorkersCompCodeMod
    IncludeRetElement
  )],
  WorkersCompCodeQueryRq => [qw(
    ListID
    FullName
    MaxReturned
    ActiveStatus
    FromModifiedDate
    ToModifiedDate
    NameFilter
    NameRangeFilter
    FromEffectiveDate
    ToEffectiveDate
    IncludeRetElement
  )],
); # end %childElements

our %mayRepeat = map { $_ => 1 } qw(
  ARRefundCreditCardRet
  AccountRef
  AccountRet
  AccountTaxLineInfoRet
  AccountType
  AppliedToTxnMod
  AppliedToTxnRet
  ApplyCheckToTxnAdd
  ApplyCheckToTxnMod
  AssignToObject
  BillPaymentCheckRet
  BillPaymentCreditCardRet
  BillRet
  BillToPayRet
  BillingRateRet
  BuildAssemblyRet
  CategoryAccountMapping
  CategoryAccountMappingMod
  ChargeRet
  CheckRet
  ClassRet
  ColData
  ComponentItemLineRet
  CreditCardChargeRet
  CreditCardCreditRet
  CreditMemoLineMod
  CreditMemoLineRet
  CreditMemoRet
  CurrencyRet
  CustomerMsgRet
  CustomerRet
  CustomerTypeRet
  DataExt
  DataExtDefRet
  DataExtRet
  DateDrivenTermsRet
  DefaultUnit
  DepositLineAdd
  DepositLineMod
  DepositLineRet
  DepositRet
  EmployeeRet
  EnabledIf
  EnabledIfNot
  EstimateLineMod
  EstimateLineRet
  EstimateRet
  ExpenseLineAdd
  ExpenseLineMod
  ExpenseLineRet
  IncludeColumn
  IncludeRetElement
  InventoryAdjustmentLineRet
  InventoryAdjustmentRet
  InvoiceLineMod
  InvoiceLineRet
  InvoiceRet
  ItemDiscountRet
  ItemFixedAssetRet
  ItemGroupLine
  ItemGroupRet
  ItemInventoryAssemblyLine
  ItemInventoryAssemblyRet
  ItemInventoryRet
  ItemLineMod
  ItemLineRet
  ItemNonInventoryRet
  ItemOtherChargeRet
  ItemPaymentRet
  ItemReceiptRet
  ItemSalesTaxGroupRet
  ItemSalesTaxRef
  ItemSalesTaxRet
  ItemServiceRet
  ItemSubtotalRet
  JobTypeRet
  JournalEntryRet
  JournalLineMod
  LinkToTxnID
  LinkedTxn
  ListDeletedRet
  ListEventSubscription
  MappingAccount
  MappingCategory
  OtherNameRet
  OwnerID
  PaymentMethodRet
  PaymentMethodType
  PayrollItemNonWageRet
  PayrollItemWageRet
  PrefillAccountRef
  PriceLevelPerItem
  PriceLevelRet
  PurchaseOrderLineMod
  PurchaseOrderLineRet
  PurchaseOrderRet
  RateEntry
  RateHistory
  ReceivePaymentRet
  ReceivePaymentToDepositRet
  RefundAppliedToTxnRet
  RelatedUnit
  RemoveFromObject
  SalesOrderLineMod
  SalesOrderLineRet
  SalesOrderRet
  SalesReceiptLineMod
  SalesReceiptLineRet
  SalesReceiptRet
  SalesRepRet
  SalesTaxCodeRet
  SalesTaxPaymentCheckLineRet
  SalesTaxPaymentCheckRet
  SalesTaxReturnLineRet
  SalesTaxReturnRet
  Service
  SetCredit
  ShipMethodRet
  StandardTermsRet
  TemplateRet
  TimeTrackingRet
  ToDoRet
  TransactionRet
  TxnDeletedRet
  TxnEventSubscription
  TxnLineDetail
  UnitOfMeasureSetRet
  VehicleMileageRet
  VehicleRet
  VendorCreditRet
  VendorRet
  VendorTypeRet
  VisibleIf
  VisibleIfNot
  WorkersCompCodeRet
); # end %mayRepeat

# This is maintained manually:
our %multipleChildren = map { $_ => 1 } qw(
  QBXMLMsgsRq              QBXMLMsgsRs
  QBXMLSubscriptionMsgsRq  QBXMLSubscriptionMsgsRs
);

#=====================================================================
# Package Finance::QBXML:

has indent => (
  is      => 'ro',
  isa     => Int,
  default => 0,
);

has version => (
  is      => 'ro',
  isa     => Str,
  default => '8.0',
);

#---------------------------------------------------------------------
sub format_XML
{
  my ($self, $node, $out) = @_;

  my $buffer;
  unless (defined $out) {
    $buffer = '';               # Indicate that we're opening $out
    open($out, '>', \$buffer);
  }

  require XML::Writer;

  my $w = XML::Writer->new(OUTPUT => $out, DATA_MODE => 1,
                           DATA_INDENT => $self->indent,
                           ENCODING => 'utf-8');

  $w->xmlDecl;
  $w->pi(qbxml => sprintf 'version="%s"', $self->version);
  $self->formatNode($w, QBXML => $node);
  $w->end;
  close $out if defined $buffer; # Don't close it if we didn't open it

  $buffer;
} # end format_XML

#---------------------------------------------------------------------
sub formatNode
{
  my ($self, $w, $tag, $node) = @_;

  my $reftype = (reftype($node) || '');

  if ($multipleChildren{$tag}) {
    # One element with multiple children in specified order (using _tag):
    my @attrs;

    if ($reftype eq 'HASH') {
      @attrs = map { $_ => $node->{$_} } grep { /^[[:lower:]]/ } keys %$node;
      # The arrayref of child nodes is stored in the '_' key:
      $node = $node->{_} || [];
    } # end if HASH

    $w->startTag($tag, @attrs);

    foreach my $n (@$node) {
      my $childTag = $n->{_tag} or croak "No _tag in child of $tag";
      $self->formatNode($w, $childTag => $n);
    }
    $w->endTag($tag);
  } # end if $multipleChildren{$tag}
  elsif ($reftype eq 'ARRAY') {
    # Multiple occurences of this tag:
    foreach my $n (@$node) {
      $self->formatNode($w, $tag => $n);
    }
  } # end elsif $node is ARRAY
  elsif ($reftype) {
    # An ordinary node formed from a hash reference:
    my (@attrs, $children);

    while (my ($k, $v) = each %$node) {
      if ($k =~ /^[[:lower:]]/) {
        push @attrs, $k, $v;
      } elsif (not $k =~ /^_/) {
        $children = 1;          # This is a node, not an attribute
        # FIXME check if valid element name?
      }
    } # end while my ($k, $v)

    if (not $children) {
      $w->emptyTag($tag, @attrs);
    } else {
      $w->startTag($tag, @attrs);

      # qbXML requires elements to appear in the correct order:
      foreach my $childTag (@{ $childElements{$tag} }) {
        $self->formatNode($w, $childTag => $node->{$childTag})
            if exists $node->{$childTag};
      } # end foreach $childTag

      $w->endTag($tag);
    } # end else node is not empty
  } # end elsif $node is a (hash) reference
  else {
    $w->dataElement($tag, $node);
  }
} # end formatNode

#---------------------------------------------------------------------
sub get_parser
{
  my ($self) = @_;

  require Finance::QBXML::Handler;
  require XML::SAX::ParserFactory;

  my $parser = XML::SAX::ParserFactory->parser(
    Handler => Finance::QBXML::Handler->new
  ) or croak "Unable to create parser";

  return $parser;
} # end get_parser

#---------------------------------------------------------------------
sub time2iso
{
  my ($self, $time) = @_;

  $time = time unless defined $time;

  my @date = gmtime($time);

  sprintf('%d-%02d-%02dT%02d:%02d:%02d',
          $date[5]+1900, $date[4]+1, @date[3,2,1,0]);
} # end time2iso

#=====================================================================
# Package Return Value:

no Moose;
__PACKAGE__->meta->make_immutable;
1;

__END__

=head1 SYNOPSIS

    use Finance::QBXML;

=for author to fill in:
    Brief code example(s) here showing commonest usage(s).
    This section will be as far as many users bother reading
    so make it as educational and exeplary as possible.


=head1 DESCRIPTION

=for author to fill in:
    Write a full description of the module and its features here.
    Use subsections (=head2, =head3) as appropriate.


=head1 INTERFACE

=for author to fill in:
    Write a separate section listing the public components of the modules
    interface. These normally consist of either subroutines that may be
    exported, or methods that may be called on objects belonging to the
    classes provided by the module.


=head1 DIAGNOSTICS

=for author to fill in:
    List every single error and warning message that the module can
    generate (even the ones that will "never happen"), with a full
    explanation of each problem, one or more likely causes, and any
    suggested remedies.

=over

=item C<< Error message here, perhaps with %s placeholders >>

[Description of error here]

=item C<< Another error message here >>

[Description of error here]

[Et cetera, et cetera]

=back


=head1 CONFIGURATION AND ENVIRONMENT

Finance::QBXML requires no configuration files or environment variables.


=head1 DEPENDENCIES

Finance::QBXML requires L<Moose>, L<XML::Writer> (for writing qbXML),
and L<XML::SAX> (for parsing qbXML).  These are all available from CPAN.

You should also install a SAX parser module, because I've encountered
problems using the L<XML::SAX::PurePerl> parser that is included with
XML::SAX.  I've been using L<XML::SAX::ExpatXS>, but other parsers
should work, too.


=head1 INCOMPATIBILITIES

None reported.


=head1 BUGS AND LIMITATIONS

No bugs have been reported.
